### ISSUE TITLE
Running examples?

### ISSUE THREAD

**Issue by icsy7867** [interlegis/ovirt-guest-agent-coreos#3]
Could you provide a couple examples on how to run this?

Assuming it needs to be a privileged container.

**Comment by fabiorauber** [comment]
There is a docker-compose.yml file in the root folder of the repository.

**Comment by fabiorauber** [comment]
There is also a docker-run.sh file in the root folder, which shows how to run without docker-compose.

**Comment by icsy7867** [comment]
Yep!  That's what I get for not taking a closer look.  Sorry for opening a ticket

**Comment by fabiorauber** [comment]
No problem!
